base_url = "https://zola-book.netlify.com"
compile_sass = true
title = "book theme"
description = "A book theme"
build_search_index = true

[markdown]
highlight_code = true

[extra]
book_number_chapters = true
