name = "book"
description = "A book theme inspired from GitBook/mdBook"
license = "MIT"
homepage = "https://github.com/Keats/book"
min_version = "0.2"

[extra]
book_number_chapters = true

[author]
name = "Vincent Prouillet"
homepage = "https://vincent.is"
